<a href="https://colab.research.google.com/github/Giri047/Algorithms/blob/master/NUMPY_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Learn with nnumpy as np

import numpy as np

# Creating array from a list
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(f"array_2d: {arr_2d}")

[1 2 3 4 5]
array_2d: [[1 2 3 4]
 [5 6 7 8]]


### List Vs Numpy

In [ ]:
import numpy as np

py_list= [1,2,4,5]
print("Multiplying list: ", py_list*2) # element wise multiplication
np_arr = np.array(py_list)
print("Multiplying numpy array: ", np_arr*2)

Multiplying list:  [1, 2, 4, 5, 1, 2, 4, 5]
Multiplying numpy array:  [ 2  4  8 10]


In [ ]:
# Checking which is more optimized during runtime
import time

start_time = time.time()
py_list = [i*2 for i in range(1000000)]
print("List operation time",time.time() - start_time)

start_time = time.time()
np_arr = np.arange(1000000) * 2
print("Numpy operation time",time.time() - start_time)



# start_time = time.time()
# np_arr = np_arr * 2
# end_time = time.time()
# print(f"Time taken for numpy array multiplication: {end_time - start_time} seconds")

List operation time 0.07285284996032715
Numpy operation time 0.005839347839355469


### Creating array from scratch

In [ ]:
import numpy as np
np_zeros= np.zeros((3, 5))
print("zeroes array:\n",np_zeros)

np_ones = np.ones((3, 6))
print("ones array:\n",np_ones)

# to get full np array where we can get any number arrays and define the rows and cols and the number that we wanna get other than 0 and 1.

full= np.full((4,6),7)
print("full array:\n",full)

zeroes array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
full array:
 [[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [ ]:
#using a random array
import numpy as np
rand_array= np.random.random((2,4))
print("random array:\n",rand_array)

random array:
 [[0.42019344 0.38734337 0.4422537  0.82182046]
 [0.36619626 0.21548022 0.81636694 0.16127984]]


In [ ]:
sequence = np.arange(2,6,2)
print("sequence_array:\n ",sequence) # it will create the array as per the range mentioned in the params.

sequence_array:
  [2 4]


## Array Properties


In [ ]:
arr= np.array([[1,2,4,5,6,],[3,6,7,8,5.5]])
print("array_shape:\n",arr.shape)
print("array_dimension:\n",arr.ndim)
print("array_datatype:\n",arr.dtype)
print("array_size:\n",arr.size)

array_shape:
 (2, 5)
array_dimension:
 2
array_datatype:
 float64
array_size:
 10


### Array Reshaping

In [7]:
import numpy as np

arr=np.arange(12)
print("Original array: \n",arr)

reshaped_arr= arr.reshape(3,4)
print("Reshaped array: \n",reshaped_arr)

# returns copy but ravel returns original
flattened_arr= reshaped_arr.flatten()
print("Flattened array: \n",flattened_arr)

raveled=np.ravel(reshaped_arr)
print("Ravel array: \n",raveled)

transposed_arr= reshaped_arr.transpose() # or reshaped_arr.T
transposed_arr= reshaped_arr.T
print("Transposed array: \n",transposed_arr)

Original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
